# Generated by Django 5.2.8 on 2025-12-18 19:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_mission_usermission'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mission',
            name='icon',
            field=models.CharField(default='🌱', max_length=50),
        ),
    ]
