# Generated by Django 5.2.8 on 2025-12-20 10:25

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_alter_mission_icon'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mission',
            name='icon',
        ),
        migrations.RemoveField(
            model_name='report',
            name='city',
        ),
        migrations.RemoveField(
            model_name='report',
            name='latitude',
        ),
        migrations.RemoveField(
            model_name='report',
            name='longitude',
        ),
        migrations.AddField(
            model_name='report',
            name='ai_analysis',
            field=models.TextField(blank=True, help_text="AI's explanation", null=True),
        ),
        migrations.AddField(
            model_name='report',
            name='ai_confidence',
            field=models.IntegerField(default=0, help_text='0-100 score'),
        ),
        migrations.AddField(
            model_name='report',
            name='location',
            field=models.CharField(default=0, max_length=255),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='mission',
            name='title',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='profile',
            name='level',
            field=models.CharField(default='Scout', max_length=50),
        ),
        migrations.AlterField(
            model_name='profile',
            name='phone_number',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='report',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='reports/'),
        ),
        migrations.AlterField(
            model_name='report',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('verified', 'Verified'), ('resolved', 'Resolved')], default='pending', max_length=20),
        ),
        migrations.AlterField(
            model_name='report',
            name='title',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='report',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='usermission',
            name='proof_image',
            field=models.ImageField(blank=True, null=True, upload_to='missions/'),
        ),
        migrations.AlterField(
            model_name='usermission',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=20),
        ),
    ]
