# Generated by Django 5.2.8 on 2025-12-20 10:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_remove_mission_icon_remove_report_city_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='report',
            name='category',
            field=models.CharField(default='Infrastructure', max_length=100),
        ),
    ]
