# Generated by Django 5.2.8 on 2025-12-22 06:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_report_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usermission',
            name='proof_image',
        ),
        migrations.AddField(
            model_name='mission',
            name='icon',
            field=models.CharField(default='🏆', max_length=50),
        ),
        migrations.AlterField(
            model_name='mission',
            name='title',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='report',
            name='ai_analysis',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='report',
            name='ai_confidence',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='usermission',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('completed', 'Completed')], default='pending', max_length=20),
        ),
    ]
