# Generated by Django 5.2.8 on 2025-12-22 10:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_remove_usermission_proof_image_mission_icon_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='usermission',
            name='ai_analysis',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='usermission',
            name='proof_image',
            field=models.ImageField(blank=True, null=True, upload_to='mission_proofs/'),
        ),
    ]
