# Generated by Django 5.2.8 on 2026-01-23 15:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_notice'),
    ]

    operations = [
        migrations.AddField(
            model_name='report',
            name='feedback',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='report',
            name='rating',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='report',
            name='resolved_image',
            field=models.ImageField(blank=True, null=True, upload_to='resolved_proofs/'),
        ),
    ]
