# Generated by Django 5.2.8 on 2026-01-25 15:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_report_feedback_report_rating_report_resolved_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='report',
            name='latitude',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='report',
            name='longitude',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='report',
            name='resolved_image',
            field=models.ImageField(blank=True, null=True, upload_to='resolved_reports/'),
        ),
    ]
