# Generated by Django 5.2.8 on 2026-03-03 07:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0013_profile_bio_profile_profile_picture'),
    ]

    operations = [
        migrations.AlterField(
            model_name='report',
            name='image',
            field=models.ImageField(blank=True, max_length=500, null=True, upload_to='reports/'),
        ),
        migrations.AlterField(
            model_name='report',
            name='resolved_image',
            field=models.ImageField(blank=True, max_length=500, null=True, upload_to='resolved_proofs/'),
        ),
        migrations.AlterField(
            model_name='report',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('verified', 'Verified'), ('rejected', 'Rejected'), ('resolved', 'Resolved')], default='pending', max_length=20),
        ),
        migrations.AlterField(
            model_name='usermission',
            name='proof_image',
            field=models.ImageField(blank=True, max_length=500, null=True, upload_to='mission_proofs/'),
        ),
    ]
