# Generated by Django 5.2.8 on 2026-03-05 14:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0014_alter_report_image_alter_report_resolved_image_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usermission',
            name='submitted_at',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
