# Generated by Django 5.2.8 on 2026-06-27 10:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0015_alter_usermission_submitted_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='report',
            name='xp_awarded',
            field=models.BooleanField(default=False),
        ),
    ]
