# Generated by Django 5.2.8 on 2026-07-02 10:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0016_report_xp_awarded'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usermission',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('completed', 'Completed'), ('rejected', 'Rejected')], default='pending', max_length=20),
        ),
    ]
